### ISSUE TITLE
Browser can't connect to the server ("Failed to open page")

### ISSUE THREAD

**Issue by ccrvlh** [pachadotdev/metabase-droplet#1]
After a few months successfully using Metabase from the DO marketplace ready-made droplet (THANKS A LOT!!!), it suddenly stopped working.

I've tried several different browsers, and none successful. Using Chrome I'm getting: "ERR_CONNECTION_REFUSED".

I don't have much knowledge on OpenJDK, but I was wondering if someone could help on what steps could I take in order to properly diagnose the problem and fix it... 

The droplet is "Active" on DO.

**Comment by pachadotdev** [comment]
Let me check that ASAP. Looks like I need to update the image!

**Comment by ccrvlh** [comment]
@pachamaltese thanks.
sorry for my ignorance, but shouldn't the server be static in terms of update? In the sens that even if I was using and out of date image version it should continue to be working? Really strange to just stop working out of the blue, without any thing happening.

Oh, important:
I checked the log from DO and it said that it "migrated" without success three times before "migrating" successfully. I didn't do anything, or asked for any migration, so don't know what that might be.

**Comment by pachadotdev** [comment]
Hi

Yes, the server remains "static" unless you run sudo apt update && apt
upgrade

Is there a way you can share a log with me *without *compromising sensitive
information?

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by ccrvlh** [comment]
Sure, what log do you need?

**Comment by pachadotdev** [comment]
DO log, where it describes the migration

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by ccrvlh** [comment]
Hm... I only have the history:


Migrate | 3 days ago | 2 minutes 3 seconds
Migrate | 3 days ago | Action did not complete
Migrate | 3 days ago | Action did not complete
Migrate | 3 days ago | Action did not complete

**Comment by pachadotdev** [comment]
Ok, let me dig into this

**Comment by pachadotdev** [comment]
@lowercase00 I checked on a fresh droplet and it's working with remote databases. 
Try powering the droplet off and re-scaling the machine, this looks pretty much like a DO issue related to migration from their side, powering off the droplet and turning it on again probably helps. Sorry I cannot help much more (I am not DO staff), you can contact me if you want to move all of your configurations to a new droplet, but that just as a community-side *unofficial* effort.
I can bet 10 dollars that what happened is that the disk got full and there was no way to store the logs before migration

**Comment by ccrvlh** [comment]
@pachamaltese thanks a lot. I also found that I was getting thousands of unwanted access requests, which looked like a machine based attack (almost 12k authentication requests). So I'm thinking all of this contributed to the droplet being down.

Anyways, it would be great to have an insight on how to retain Metabase configuration (dashboards and etc), I had tens of dashboards setup, it would be a shame to loose them all.

Thanks a lot again!

**Comment by pachadotdev** [comment]
Whaaaat? Do you need help enabling https?

**Comment by pachadotdev** [comment]
To export configurations, please check
https://github.com/metabase/metabase/issues/6485

**Comment by ccrvlh** [comment]
@pachamaltese thanks, I installed Fail2Ban and now enabling https to try to avoid that...
unfortunately I couldn't find any info on how to export Metabase configurations from the linux command line, so probably I'm just going to start a new droplet and start from scratch.

If you have any insight on how to export from my current droplet and import to the new one from the Linux command line that would be great!

Thanks a lot!

**Comment by ccrvlh** [comment]
@pachamaltese also, if is not too much trouble, my I ask you what's the logic behind the script? I found a Metabase docker image, but also saw on the description that it uses openJDK, how exactly the droplet works? What server does it use? Is Metabase running on docker, openJDK? I couldn't find apache/ngix running, so I'm a bit lost... thanks!!

**Comment by pachadotdev** [comment]
Try this tool https://github.com/elevate/elevate.metabase.tools

But, if there are no successful logs from outside, I'd turn off the droplet
and scale it, then start the services again and change all passwords.

One effective solution could be to close ports and allow just connections
vis ssh tunnel with ssh keys instead of typed passwords. DO has tutorials
to do that.

Best,

**Comment by pachadotdev** [comment]
@lowercase00 run this
```
sudo last -a | more
```
if you see something like a IP that you don't recognize, change passwords now

but if you run
```
sudo lastb -a | more
```
it will show failed logins, there should be many of them based on what you describe
