### ISSUE TITLE
Upgrading metbase

### ISSUE THREAD

**Issue by fpun** [pachadotdev/metabase-droplet#4]
Hi,

What would be the easiest way to upgrade to the latest version of metabase without deleting existing questions / dashboards etc.?

**Comment by pachadotdev** [comment]
You can update metabase version in a "normal" way.
https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase

**Comment by fpun** [comment]
Thank you, so just to clarify does the droplet run docker or the JAR file?

**Comment by pachadotdev** [comment]
Jar

**Comment by fpun** [comment]
Thanks that worked for me

**Comment by gregorojstersek** [comment]
Just did an upgrade to 0.50.10 and it works good with the [Upgrading a JAR running in production as a service](https://www.metabase.com/docs/v0.50/installation-and-operation/upgrading-metabase#upgrading-a-jar-running-in-production-as-a-service) 

The metabase folder is located in opt/metabase -> just changing the jar file and restarting the service does the trick!
