### ISSUE TITLE
How do I install metabase updates

### ISSUE THREAD

**Issue by bondgeek** [pachadotdev/metabase-droplet#5]
After creating a droplet and starting up metabase, I get the following message in the admin panel.

`Metabase 0.34.2 is available. You're running 0.32.10`

- clicking the Update button takes me to pages in the metabase docs, but it's not clear which option to take to update
- it would be great if this step was included in the README

Thanks for this package, btw.  Super helpful

**Comment by pachadotdev** [comment]
welcome!!
I need to update the image then :)

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by pachadotdev** [comment]
@bondgeek Hi! please find the updated image here: https://marketplace.digitalocean.com/apps/metabase

The migration shall be straightforward

**Comment by bondgeek** [comment]
Thanks!
